spring.kafka.producer.properties.schema.registry.url=https://psrc-abc.us-east-2.aws.confluent.cloud
spring.kafka.producer.properties.auto.register.schemas=true
spring.kafka.producer.properties.use.latest.version=true
spring.kafka.producer.properties.basic.auth.credentials.source=USER_INFO
